
[general]
	announce_new_song = 0
	link_mode = 1
	first_time = false
	mod_mode = -1
	notification_album_art_location = 1
	music_service = "spotify"
	announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"

[servers]
	allowed_servers = ""
	send_songs_to_servers = false

[rendering]
	controls = false
	display_mode = 2
	position_x_offset = 1.0
	position_y_offset = 1.0
	anchor_point = 7
	render_type = 2

[login]
	refresh_token = "AQAKvDwklnZbuDwWC1b1fTaTLsEkoZTyh0cJ-bhHHsNcLAv-mvR71emQ-yb90e8Y0heRxyHH35C-oTI0c3AJtYQV9RZphUFwgmgdXJYZijEWajh_g4I8_Dxri0k8ucHYYeg"
	spotify_login_token = "BQBlp4rLVyBHyZ3KCcKdLFBtYxb5a4uQ02BhQHfqBZ486CiIhY21ZKdR8FISjUxoItEoTjvBNMyvR4nGu2iXz-K4uBLV69GX9q5uSgHBKhvYGlX7405KXBkO9vnhWyhYZ-5WUQB6F8B7faBsxhdBYes6JhSdkeKh1tVZRyv7ithBJBLgn4APV2fVZj9VDYnoqdx_cGbfPxTtfIZe2ob4bOA"
	ytmd_token = ""
	service_port = 8880

