
[general]
	announce_new_song = 0
	link_mode = 1
	first_time = false
	mod_mode = -1
	notification_album_art_location = 1
	music_service = ""
	announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"

[servers]
	allowed_servers = ""
	send_songs_to_servers = false

[rendering]
	controls = false
	display_mode = 2
	position_x_offset = 1.0
	position_y_offset = 1.0
	anchor_point = 7
	render_type = 2

[login]
	refresh_token = "AQC69F4Mq6mI6AGXBeY3AqY4zCQ6kFcN39T4c_HZjsGfNPhRMyurB_lBEAS3irAo-H-xN18axxxdMFMUNfG0YQbda5WIcaToAHft-IhhwBvCod-OVw6XD23Z0hvJLu3q-Ds"
	ytmd_token = ""
	service_port = 8880

